name: release

on:
  workflow_dispatch:
  push:
    tags: '*'

jobs:
  packages:
    permissions:
        contents: write
    runs-on: ubuntu-latest
    env:
      BUILDER: "Github Actions <noreply@github.com>"

    steps:
    - uses: actions/checkout@v2

    - name: install dependencies
      run: |
        sudo wget https://github.com/jgm/pandoc/releases/download/3.1.11.1/pandoc-3.1.11.1-1-amd64.deb
        sudo dpkg -i pandoc-3.1.11.1-1-amd64.deb
        rm -f pandoc-3.1.11.1-1-amd64.deb

    - name: create packages
      run: |
        BUILD_GOARCH=amd64 BUILD_GOOS=freebsd make build-standalone
        BUILD_GOARCH=amd64 BUILD_GOOS=linux   make build-standalone
        BUILD_GOARCH=amd64 BUILD_GOOS=darwin  make build-standalone
        BUILD_GOARCH=arm64 BUILD_GOOS=darwin  make build-standalone

    - name: create release
      run: make github-release
      env:
        GH_TOKEN: ${{ github.token }}
